# Site settings
title: Mapping Community
subtitle: An AHRC funded participatory big-data initiative
email: j.kidwell@bham.ac.uk
description: resourcing the grassroots, generating open geospatial data & highlighting local sustainability
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mapping.community" # the base hostname & protocol for your site
author: Jeremy Kidwell
street_address: University of Birmingham
city: Birmingham
state: 
zip_code: B15 2TT
country: United Kingdom
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/kidwellj/mapping.community
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kidwellj

# Build settings
markdown: kramdown

sass:
  style: compressed
